# Generated by Django 6.0.2 on 2026-03-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbenchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('stage', 'Stage'), ('prod', 'Production')], max_length=10)),
                ('request_id', models.CharField(max_length=50)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('url', models.TextField()),
                ('overall_status', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, max_length=50, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('submitter', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cookies', models.JSONField(blank=True, null=True)),
                ('sub_jobs', models.JSONField(blank=True, null=True)),
                ('queue', models.IntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
