# Generated by Django 6.0.2 on 2026-03-30 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0002_requestgroup_requestgroupitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbenchrequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='workbench.requestgroup'),
        ),
        migrations.AlterField(
            model_name='requestgroupitem',
            name='request_id',
            field=models.CharField(max_length=50),
        ),
    ]
