# Generated by Django 6.0.2 on 2026-03-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0003_workbenchrequest_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='requestgroup',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='groups', to='workbench.service'),
        ),
        migrations.AddField(
            model_name='workbenchrequest',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='requests', to='workbench.service'),
        ),
    ]
