# Generated by Django 6.0.2 on 2026-03-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0004_service_requestgroup_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestgroupitem',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='group_items', to='workbench.service'),
        ),
    ]
