# Generated by Django 6.0.2 on 2026-04-01 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0005_requestgroupitem_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestgroupitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
