# Generated by Django 6.0.2 on 2026-04-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0006_requestgroupitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbenchrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
