SERVICES = [
"Decision",
"Next Request",
"999 Reports",
"Enhanced 999 Reports",
"Generic JCL",
"JCL Job",
"Address Hygiene",
"Canadian Hygiene",
"Email Hygiene",
"Name Parse",
"Analytic Base",
"B2C Link",
"Business Email Enhancement",
"Business Enhancement",
"Canadian Business Enhancement",
"Consumer Email Enhancement",
"Consumer Enhancement",
"Culture Code",
"Deceased",
"Donor Data (Apogee)",
"Executive Rollup",
"Geo Analytic Base",
"Geo Enhancement",
"Match Code",
"Phone Enhancement",
"ProfileFuse",
"Public Record Enhancement",
"Radial Name Matching",
"Reverse Email",
"Reverse Telephone",
"Suppression",
"TAVS",
"Transactional",
"Wireless Enhancement",
"Wireless Information",
"Consolidation",
"Dup Identification",
"Join Two Files",
"Auto Bill",
"Distribution",
"MZPlus Interface",
"Auto Convert",
"Convert to Delimited",
"Convert to Fixed I",
"Convert to Fixed II",
"Data Manipulation",
"Date Dollar",
"File Manipulation",
"Post Convert",
"Data Profile",
"DPWorkFlow",
"Dump File",
"Header File Details",
"Header Record",
"IConv",
"Nthing",
"Quality Assurance",
"Select and Assign",
"Sequence by Keycode",
"Sort",
"Sort Merge",
"Tally"

]
SERVICES.append("KKP")
